from dearpygui.core import *
from dearpygui.simple import *


from functions import *

set_main_window_size(800,680)
set_global_font_scale(1.30)
set_theme("Classic")
set_main_window_title("AIO")
set_main_window_resizable(False)
add_additional_font(file="Roboto-Medium.ttf")



with window("File downloader", width=780, height=660, no_resize=True , no_move=True, no_close=True, no_collapse=True):
    set_window_pos("File downloader", 0, 0)
    add_text("Media section")
    add_separator()
    add_child("Downloading", width=380, height=150)
    add_text("MP4")
    add_separator()
    add_spacing(count=5)
    add_input_text("URL", width=330, label="URL")
    add_spacing(count=5)
    add_button("Download MP4", callback=download_video, label="Download video")
    add_same_line()
    add_text("or")
    add_same_line()
    add_button("Download Playlist(MP4)", callback=download_youtube_mp4_playlist, label="Download Playlist")
    end()
    add_same_line()
    add_child("Downloading2", width=380, height=150)
    add_text("MP3")
    add_separator()
    add_spacing(count=5)
    add_input_text("URL2", width=330, label="URL")
    add_spacing(count=5)
    add_button("Download MP3", callback=download_audio, label="Download track")
    add_same_line()
    add_text("or")
    add_same_line()
    add_button("Download Playlist(MP3)", callback=download_youtube_mp3_playlist, label="Download Playlist")
    end()

    add_child("Soundcloud_downloading", width=380, height=300)
    add_text("Soundcloud")
    add_separator()
    add_spacing(count=5)
    add_input_text("URL3", width=330, label="URL")
    add_spacing(count=5)
    add_button("Download Track", callback=download_soundcloud_mp3, label="Download track")
    add_same_line()
    add_text("or")
    add_same_line()
    add_button("Download Playlist", callback=download_soundcloud_playlist, label="Download Playlist")
    add_spacing(count=5)
    add_text("Artwork")
    add_separator()
    add_spacing(count=1)
    add_text("                                ") # ultra professional padding
    add_same_line()
    add_drawing("artwork_image", width=120, height=120)
    end()
    add_same_line()
    add_child("youtube search", width=380, height=300)
    add_text("YouTube search")
    add_separator()
    add_input_text("youtube_search", width=300, label="Search")
    add_listbox(name="results_listbox", width=300, label="Results",num_items=9)
    add_spacing(count=2)
    add_button("Search", callback=search_for_videos)
    add_same_line()
    add_button("Send URL to downloader",width=239, callback=set_links)
    end()

    add_logger("logger_general", width=770, height=130, clear_button=False, auto_scroll_button=False, copy_button=False, filter=False)

start_dearpygui()
